/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rabalais.regex2english;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // @Test public void processTree1() {
    //     App test = new App();


    //     String tree1 = test.processTree("[ab]");

    //     System.out.println(tree1);


    //     assertTrue(tree1.equals("'[ab]'(0)"));

    // }
    // @Test public void processTree1() {
    //     App test = new App();

    //     String tree1 = test.processTree("[ab]").replaceAll(" ","");
    //     assertTrue(tree1.equals("\'[ab]\'(0)"));
        
    // }

    // public static boolean compare(){

    // }
}
