/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli;

import java.io.IOException;
import java.io.FileReader;
import java.io.BufferedReader;

import java.util.Arrays;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.TimeUnit;

import com.googlecode.lanterna.*;
import com.googlecode.lanterna.terminal.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.graphics.*;
import com.googlecode.lanterna.TextColor.*;
import com.googlecode.lanterna.SGR;
import com.googlecode.lanterna.input.*;

public class CLI {

    private static Panel mainPanel;
    private static Panel topPanel;
    private static Panel inputPanel;
    private static Panel bottomPanel;
    private static Panel buttonsPanel;
    private static TextBox displayText;
    private static TextBox inputTextBox;
    private static Button enterButton;
    private static Button clearButton;
    private static Button guideButton;
    private static Button quitButton;

    private static String guide;

    public static void main(String[] args) throws IOException {
        init();
    }
    
    private static void init() throws IOException {
        Terminal terminal = new DefaultTerminalFactory().createTerminal();
        Screen screen = new TerminalScreen(terminal);

        screen.startScreen();

        WindowBasedTextGUI textGUI = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLACK));
        SimpleTheme theme = new SimpleTheme(TextColor.ANSI.GREEN, TextColor.ANSI.BLACK, SGR.BOLD);
        textGUI.setTheme(theme);

        BasicWindow window = new BasicWindow();
        window.setHints(Arrays.asList(Window.Hint.CENTERED));

        mainPanel = new Panel();
        topPanel = new Panel();
        bottomPanel = new Panel(new GridLayout(2));
        inputPanel = new Panel();
        buttonsPanel = new Panel();

        displayText = new TextBox();
        displayText.setCaretWarp(true);
        inputTextBox = new TextBox("-t ^(?=.*\\d\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=shadowJar\\s).{8,16}$ ", TextBox.Style.MULTI_LINE);

        enterButton = new Button("Enter", () -> {
            String inputText = inputTextBox.getText();
            try {
                if (inputText == null || inputText.equals("")) {
                    displayText.setText("Please enter a valid input.");
                } else {
                    String cmd = "gradle run --args=\"" + inputText + "\"";
                    ProcessBuilder runGradle = new ProcessBuilder("bash", "-c", cmd);
                    Process process = runGradle.start();

                    int exitCode = process.waitFor();

                    if (exitCode == 0) {
                        FileReader fileReader = new FileReader("./cli/out.txt");
                        BufferedReader bufferedReader = new BufferedReader(fileReader);

                        StringBuilder sb = new StringBuilder();
                        String line = bufferedReader.readLine();
                        while (line != null) {
                            sb.append(line);
                            sb.append(System.lineSeparator());
                            line = bufferedReader.readLine();
                        }
                        fileReader.close();
                        bufferedReader.close();
                        process.destroy();

                        String content = sb.toString();
                        if (!content.equals("")) {
                            displayText.setText(content);
                        } else {
                            displayText.setText("Input could not be read.");
                        }
                    } else {
                        System.out.println("Backend parsing failed.");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Frontend can't reach backend.");
            }
            displayText.takeFocus();

        });

        clearButton = new Button("Clear", () -> {
            clear();
        });

        guideButton = new Button("Guide", () -> {
            showGuide();
        });

        quitButton = new Button("↳Quit", () -> {
            System.exit(0);
        });

        topPanel.addComponent(displayText);

        inputPanel.addComponent(inputTextBox);

        buttonsPanel.addComponent(enterButton);
        buttonsPanel.addComponent(clearButton);
        buttonsPanel.addComponent(guideButton);
        buttonsPanel.addComponent(quitButton);

        bottomPanel.addComponent(buttonsPanel);

        mainPanel.addComponent(topPanel.withBorder(Borders.doubleLine("Regex2English")));
        mainPanel.addComponent(inputPanel.withBorder(Borders.doubleLine("Input")));
        mainPanel.addComponent(bottomPanel.withBorder(Borders.doubleLine()));

        setSizeOfAllComponents(screen.getTerminalSize());

        window.setComponent(mainPanel);

        terminal.addResizeListener(new TerminalResizeListener() {
            @Override
            public void onResized(Terminal terminal, TerminalSize newSize) {
                setSizeOfAllComponents(newSize);
                try {
                    screen.refresh();
                } catch (Exception e) {
                    System.out.println("Terminal window resize failed!");
                }
            }
        });
        textGUI.addWindowAndWait(window);
    }

    private static void setSizeOfAllComponents(TerminalSize size) {
        //main panel:
        mainPanel.setPreferredSize(size);
        GridLayout mainPanelLayout = new GridLayout(1)
                .setLeftMarginSize(1)
                .setRightMarginSize(1)
                .setTopMarginSize(0)
                .setBottomMarginSize(0);
        mainPanelLayout.createLayoutData(GridLayout.Alignment.CENTER, GridLayout.Alignment.END, true, true);
        mainPanel.setLayoutManager(mainPanelLayout);

        int cols = size.getColumns();
        int rows = size.getRows();

        // bottom panel:
        bottomPanel.setPreferredSize(new TerminalSize(cols, 20));

        //input panel:
        inputPanel.setPreferredSize(new TerminalSize(cols, 20));
        //buttons panel:
        buttonsPanel.setPreferredSize(new TerminalSize(cols, 18));

        // textboxes:
        inputTextBox.setPreferredSize(new TerminalSize(cols, 20));

        // buttons:
        enterButton.setPreferredSize(new TerminalSize(cols, 2));
        clearButton.setPreferredSize(new TerminalSize(cols, 2));
        guideButton.setPreferredSize(new TerminalSize(cols, 2));
        quitButton.setPreferredSize(new TerminalSize(cols, 2));

        // top panel:
        topPanel.setPreferredSize(new TerminalSize(cols, rows));
        displayText.setPreferredSize(new TerminalSize(cols, rows));
    }

    private static void clear() {
        displayText.setText("");
        inputTextBox.setText("");
    }

    private static void showGuide() {
        guide = "## Regex2English Guide\n" +
                "This program converts regular expressions into human-readable English descriptions.\n\n" +
                "### Usage:\n" +
                "1.  Input Field: Enter your regular expression in the 'Input' text box.\n" +
                "    * Example: `^\\d{3}-\\d{2}-\\d{4}$`\n" +
                "    * The current default pattern shown is a strong password regex for demonstration.\n" +
                "2.  Enter Button: Click 'Enter' or press Enter in the input field to process the regex.\n" +
                "3.  Display Area: The 'Regex2English' area will show the English translation.\n" +
                "    * If there's an issue with the regex or backend, an error message will appear.\n\n" +
                "### Other Buttons:\n" +
                "* Clear: Clears both the input and display areas.\n" +
                "* Guide: Displays this guide.\n" +
                "* Quit: Exits the application.\n\n" +
                "Enjoy converting your regexes!"; // setup man page with picocli
        displayText.setText(guide);
    }
}