/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;

import com.googlecode.lanterna.*;
import com.googlecode.lanterna.terminal.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.graphics.*;
import com.googlecode.lanterna.TextColor.*;
import com.googlecode.lanterna.SGR;

public class CLI{

    private static Panel mainPanel;
    private static Panel topPanel;
    private static Panel bottomPanel;
    private static TextBox displayText;
    private static TextBox inputTextBox;
    private static Button enterButton;

    public static void main(String[] args) throws IOException{

        Terminal terminal = new DefaultTerminalFactory().createTerminal();
        Screen screen = new TerminalScreen(terminal);
        screen.startScreen();

        WindowBasedTextGUI textGUI = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLACK));
        SimpleTheme theme = new SimpleTheme(TextColor.ANSI.GREEN, TextColor.ANSI.BLACK, SGR.BOLD);
        textGUI.setTheme(theme);

        BasicWindow window = new BasicWindow();
        window.setHints(Arrays.asList(Window.Hint.CENTERED));
        
        mainPanel = new Panel();
        topPanel = new Panel();
        bottomPanel = new Panel();
        
        displayText = new TextBox(new TerminalSize(screen.getTerminalSize().getColumns(), screen.getTerminalSize().getRows() * 85 / 100));
        inputTextBox = new TextBox(new TerminalSize(screen.getTerminalSize().getColumns(), screen.getTerminalSize().getRows() *  1 / 10), "-k [abcd]", TextBox.Style.MULTI_LINE);
  
        setSizeOfAllComponents(screen.getTerminalSize());

        topPanel.addComponent(displayText);
        mainPanel.addComponent(topPanel.withBorder(Borders.singleLine("Regex2English")));

        enterButton = new Button("Enter", () -> {
            String inputText = inputTextBox.getText();
            try{     

                String cmd = "gradle run --args=\"" + inputText + "\"";
                ProcessBuilder runGradle = new ProcessBuilder("bash", "-c", cmd);

                Process process = runGradle.start();
                BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                
                StringBuilder sb = new StringBuilder();
                String line = bufferedReader.readLine();
                while (line != null) {
                    sb.append(line);
                    sb.append(System.lineSeparator());
                    line = bufferedReader.readLine();                
                }
            
                String content = sb.toString();
                // make this more robust
                content = content.substring(content.indexOf(":App:run") + 9, content.indexOf("BUILD SUCCESSFUL"));
                if(!content.equals("")){
                  displayText.setText(content);
                }
            }
            catch(Exception e){
                e.printStackTrace();
                System.out.println("Frontend can't reach backend.");
            }

        });


        bottomPanel.addComponent(inputTextBox);
        bottomPanel.addComponent(enterButton);
        
        mainPanel.addComponent(bottomPanel.withBorder(Borders.singleLine("Input")));
        window.setComponent(mainPanel);
  
        terminal.addResizeListener(new TerminalResizeListener() {
            @Override
            public void onResized(Terminal terminal, TerminalSize newSize) {
                setSizeOfAllComponents(newSize);
                try {
                    terminal.flush();
                }
                catch(Exception e) {
                    System.out.println("Terminal window resize failed!");
                }
            }
        });

        textGUI.addWindowAndWait(window); 
    }

    private static void setSizeOfAllComponents(TerminalSize size){

        //main panel:
        mainPanel.setPreferredSize(size);
        GridLayout mainPanelLayout =  new GridLayout(1)    
        .setLeftMarginSize(1)
        .setRightMarginSize(1);
        mainPanelLayout.createLayoutData(GridLayout.Alignment.CENTER,GridLayout.Alignment.END,true,true);
        mainPanel.setLayoutManager(mainPanelLayout);

        // top panel:
        topPanel.setPreferredSize( new TerminalSize(size.getColumns(),size.getRows() * 85 / 100));
        topPanel.setLayoutData(GridLayout.createLayoutData(GridLayout.Alignment.CENTER, GridLayout.Alignment.CENTER));

        //bottom panel:
        bottomPanel.setPreferredSize(new TerminalSize(size.getColumns(), size.getRows() * 1 / 10));
        bottomPanel.setLayoutData(GridLayout.createLayoutData(GridLayout.Alignment.CENTER, GridLayout.Alignment.END));

        // textboxes:
        displayText.setSize(new TerminalSize(size.getColumns(), (size.getRows() * 88 / 100)));
        inputTextBox.setSize(new TerminalSize(size.getColumns(), size.getRows() *  1 / 10));

    }

}

