/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regex2english;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    Listener a  = new Listener();



    }
}
